### ISSUE TITLE
Everyone is skipping through the tutorial...

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#182] opened 2017-05-30 02:36 UTC
Make better tutorial. AI will ask player to confirm ship functions. 

_Players want to explore the unknown, so limit the unknown until they are ready or Or have the background reveal information on where they need to go?_

**Level 1**

1. Have AI tell player to run through a test to confirm ship is working. Show them a coordinate on the map that has shown interest. Tell them to view this location by using the map. 

2. Have them move the ship towards coordinate [390,562].

3. This coordinate revels an asteroid field. Tell players the AI has detected a high amount of material you use to upgrade your ship just past the field, you need to get past the field.

3. Take advantage of parallax scrolling and create an "asteroid field." Have players get through this field and take damage by a crash at the end (if they didn't take enough damage earlier on)

4. Have players repair their ship.

5. Have players upgrade their ship so they can build new ships to collect resources.
Inform the player their current ship can build other ships each with a special function.

6. Build ship to collect scrap.

8. Collect firearms among the scrap use it to build fighters.

7. Collect special portal key among the scrap, use it to build a portal ship.

8. Inform the player with a portal ship they can open a portal gate to the next zone.

Player can now use their jump ship to get to level map.

**Level 2**

1. Tell players about building a drydock to enable stronger fighters.
2. Warn players only "fighters" are able to shoot, and other ships should run from any enemies or use other means to avoid notice (cloaking, hide in environment, use traps etc)
3. Tell player portal ship needs to cool down before you can jump to the next level.

**Comment by josefnpat** [comment] 2017-05-31 22:19
This feels like a reiteration/dupe of #54

>Make better tutorial. AI will ask player to confirm ship functions.

This is fine and dandy to say, but *HOW* is this done?

**Comment by softsound** [comment] 2017-06-01 00:25
I'll work on the tutorial myself and try and code it.

**Comment by josefnpat** [comment] 2017-06-01 02:18
dupe of #54

**Closed** 2017-06-01 02:18 UTC
