### ISSUE TITLE
Multiplayer GUI on left camera move line, needs to move right

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#405] opened 2018-06-11 01:03 UTC
Whole GUI needs to nudged over to the right a few pixels in multiplayer. The left most buttons are on the camera move line so if any anyone tries to click the left most button they will move the camera left as well. 
Single player appears to be right enough if you want a reference.

**Comment by josefnpat** [comment] 2018-06-11 01:38
Duplicate of #403

**Comment by josefnpat** [comment] 2018-06-11 22:47
Sorry not a dupe

**Closed** 2018-06-11 23:15 UTC
Labels: bug
