### ISSUE TITLE
Game Crash during NAGN Oct 25th Demo

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#616] opened 2018-10-30 02:15 UTC
During the demo, one incident recorded with a crash:
![crashoct25](https://user-images.githubusercontent.com/34079393/47691168-055cbb80-dbbf-11e8-9c56-da6fd58a9bb3.png)

My recollection on what happened:
- Player A was on Slave machine. Player B was on Host machine.
- Slave machine was not set to ready. Host machine was set to ready.
- Slave machine attempted to change game mode from `full game` to `demo`.
- Game crashed on both machines.

Below are an attempt at repro steps.
_Operating System_
Windows 10 (64bit)

_Version_
client n/a
server n/a

_Repro_
0. Machines should be connected locally (our demo's are set up with an ethernet connection)
1. a. Host machine: Host a game and enter the lobby
1. b. Slave machine: Connect to the hosted game and enter the lobby.
2. Either machine: Set up the game normally
3. a. Host machine clicks ready.
3. b. Slave machine is not ready. Slave machine attempts to change game mode from 'Full game' to 'Demo'.

_Expected_
Parameter should change from Full game' to 'Demo'. Then Slave machine can bet set to ready.

_Result_
Game crashes on both machines.

**Comment by josefnpat** [comment] 2019-03-22 17:46
Dupe of #604!

**Closed by josefnpat** 2019-03-22 17:46 UTC
Labels: bug, multiplayer
